Repository Villanueva-del-Trabuco-EGC/decide, pull requests merged in 2022-12, with the labels that each got.

#13 Subiendo la funcionalidad estable a master
  .github/workflows/django.yml
  decide/authentication/backends.py
  decide/authentication/locale/es_ES/LC_MESSAGES/django.po
  decide/authentication/templates/authentication/register.html
  decide/authentication/templates/template_activate_account.html
  decide/authentication/tests.py
  decide/authentication/tokens.py
  decide/authentication/urls.py
  decide/authentication/views.py
  decide/base/locale/es_ES/LC_MESSAGES/django.po
  decide/base/templates/base.html
  decide/booth/locale/es_ES/LC_MESSAGES/django.po
  decide/booth/templates/booth/booth.html
  decide/booth/urls.py
  decide/booth/views.py
  decide/census/locale/es_ES/LC_MESSAGES/django.po
  decide/census/templates/census/census.html
  decide/census/templates/export_census.html
  decide/census/templatetags/__init__.py
  decide/census/templatetags/index.py
  decide/census/urls.py
  decide/census/views.py
  decide/decide/locale/es_ES/LC_MESSAGES/django.po
  decide/decide/settings.py
  decide/decide/urls.py
  decide/gateway/locale/es_ES/LC_MESSAGES/django.po
  decide/mixnet/locale/es_ES/LC_MESSAGES/django.po
  decide/postproc/locale/es_ES/LC_MESSAGES/django.po
  decide/store/locale/es_ES/LC_MESSAGES/django.po
  decide/visualizer/locale/es_ES/LC_MESSAGES/django.po
  decide/visualizer/static/graph.js
  decide/visualizer/templates/visualizer/visualizer.html
  decide/voting/locale/es_ES/LC_MESSAGES/django.po
  decide/voting/migrations/0004_voting_escaños.py
  decide/voting/migrations/0005_auto_20221116_1915.py
  decide/voting/migrations/0006_auto_20221119_1111.py
  decide/voting/migrations/0007_auto_20221119_1119.py
  decide/voting/migrations/0008_auto_20221119_1128.py
  decide/voting/models.py
  decide/voting/serializers.py
  decide/voting/tests.py
  requirements.txt
Labels: desarrollo, sincronización

#14 Subidos cambios part-2 a repositorio principal
  decide/authentication/templates/template_activate_account.html
  decide/authentication/tests.py
  decide/visualizer/templates/visualizer/visualizer.html
  decide/visualizer/tests.py
  decide/voting/tests.py
Labels: bug, desarrollo, testeo, sincronización

#18 [FIX] Ejecución de acciones
  .github/workflows/releases_workflow.yml
Labels: bug, desarrollo

#20 [FIX] Segundo arreglo de Actions
  .github/workflows/django.yml
Labels: fix

#24 Nuevo formato en la importación de censo
  decide/census/views.py
  requirements.txt
Labels: desarrollo

#25 Actualización de master con funcionalidad estable
  .github/workflows/django.yml
  .github/workflows/releases_workflow.yml
  decide/authentication/locale/en_US/LC_MESSAGES/django.po
  decide/authentication/locale/es_ES/LC_MESSAGES/django.po
  decide/authentication/templates/authentication/register.html
  decide/authentication/templates/template_activate_account.html
  decide/authentication/tests.py
  decide/base/locale/en_US/LC_MESSAGES/django.po
  decide/base/templates/base.html
  decide/booth/locale/en_US/LC_MESSAGES/django.po
  decide/booth/locale/es_ES/LC_MESSAGES/django.po
  decide/booth/templates/booth/booth.html
  decide/booth/templates/booth/votings.html
  decide/booth/tests.py
  decide/booth/urls.py
  decide/booth/views.py
  decide/census/census_utils.py
  decide/census/forms.py
  decide/census/locale/en_US/LC_MESSAGES/django.po
  decide/census/locale/es_ES/LC_MESSAGES/django.po
  decide/census/templates/census/census.html
  decide/census/templates/errors.html
  decide/census/templates/export_census.html
  decide/census/tests.py
  decide/census/views.py
  decide/decide/locale/en_US/LC_MESSAGES/django.po
  decide/decide/settings.py
  decide/gateway/locale/en_US/LC_MESSAGES/django.po
  decide/mixnet/locale/en_US/LC_MESSAGES/django.po
  decide/postproc/locale/en_US/LC_MESSAGES/django.po
  decide/store/locale/en_US/LC_MESSAGES/django.po
  decide/visualizer/locale/en_US/LC_MESSAGES/django.po
  decide/visualizer/locale/es_ES/LC_MESSAGES/django.po
  decide/visualizer/static/graph.js
  decide/visualizer/templates/visualizer/visualizer.html
  decide/visualizer/tests.py
  decide/visualizer/views.py
  decide/voting/locale/en_US/LC_MESSAGES/django.po
  decide/voting/migrations/0004_question_classic.py
  decide/voting/migrations/0005_auto_20221120_1354.py
  decide/voting/migrations/0009_merge_20221206_1713.py
  decide/voting/models.py
  decide/voting/serializers.py
  decide/voting/tests.py
  docker/Dockerfile
  requirements.txt
Labels: sincronización

#29 [DESARROLLO] Añadido cambios para generar imagen docker
  .github/workflows/docker.yml
  docker/docker-compose.yml
Labels: desarrollo

#28 Actualización de la rama con la ultima funcionalidad de decide-part-1
  decide/census/tests.py
  decide/census/views.py
  decide/visualizer/locale/es_ES/LC_MESSAGES/django.po
  decide/visualizer/templates/visualizer/visualizer.html
  decide/visualizer/tests.py
Labels: sincronización

#27 [Test] Añadidos test básicos sobre voto por preferencia
  decide/visualizer/tests.py
  decide/voting/tests.py
Labels: testeo

#34 Actualización con funcionalidad nueva de part-1
  .github/workflows/releases_workflow.yml
  .gitignore
  README.md
  decide/booth/locale/en_US/LC_MESSAGES/django.po
  decide/booth/locale/es_ES/LC_MESSAGES/django.po
  decide/booth/templates/booth/booth.html
  decide/booth/templates/booth/votings.html
  decide/booth/tests.py
  decide/booth/urls.py
  decide/booth/views.py
  decide/census/census_utils.py
  decide/census/forms.py
  decide/census/tests.py
  decide/decide/settings.py
  decide/decide/urls.py
  decide/visualizer/forms.py
  decide/visualizer/templates/visualizer/visualizer.html
  decide/visualizer/tests.py
  decide/visualizer/urls.py
  decide/visualizer/views.py
  docker/Dockerfile
  docker/docker-nginx.conf
  requirements.txt
Labels: sincronización

#35 Últimos cambios a las funcionalidades de nuestro part
  .github/workflows/django.yml
  .github/workflows/docker.yml
  .github/workflows/releases_workflow.yml
  decide/authentication/templates/template_activate_account.html
  decide/authentication/views.py
  decide/census/templates/census/census.html
  decide/census/testfiles/voters.csv
  decide/census/testfiles/voters.txt
  decide/census/testfiles/voters.xlsx
  decide/census/tests.py
  decide/census/views.py
  decide/decide/settings.py
  decide/visualizer/tests.py
  decide/voting/models.py
  decide/voting/tests.py
  docker/Dockerfile
  docker/docker-compose.yml
  requirements.txt
Labels: desarrollo, testeo, sincronización

#36 Hotfix para solucionar actions
  decide/census/tests.py
Labels: bug, fix

#38 Sincronización de los ultimos cambios - Release 1.1
  .github/workflows/django.yml
  .github/workflows/releases_workflow.yml
  .gitignore
  README.md
  decide/authentication/templates/template_activate_account.html
  decide/authentication/views.py
  decide/booth/locale/en_US/LC_MESSAGES/django.po
  decide/booth/locale/es_ES/LC_MESSAGES/django.po
  decide/booth/templates/booth/booth.html
  decide/booth/templates/booth/votings.html
  decide/booth/tests.py
  decide/booth/urls.py
  decide/booth/views.py
  decide/census/census_utils.py
  decide/census/forms.py
  decide/census/templates/census/census.html
  decide/census/testfiles/voters.csv
  decide/census/testfiles/voters.txt
  decide/census/testfiles/voters.xlsx
  decide/census/tests.py
  decide/census/views.py
  decide/decide/settings.py
  decide/decide/urls.py
  decide/visualizer/forms.py
  decide/visualizer/locale/es_ES/LC_MESSAGES/django.po
  decide/visualizer/templates/visualizer/visualizer.html
  decide/visualizer/tests.py
  decide/visualizer/urls.py
  decide/visualizer/views.py
  decide/voting/models.py
  decide/voting/tests.py
  docker/Dockerfile
  docker/docker-compose.yml
  docker/docker-nginx.conf
  requirements.txt
Labels: sincronización

#39 [FIX] Arreglo de visualizer
  decide/visualizer/templates/visualizer/visualizer.html
  docker/Dockerfile
Labels: fix

#40 [Fix] Localización de script de gráficas cambiado
  decide/visualizer/static/graph.js
  decide/visualizer/templates/visualizer/visualizer.html
Labels: fix

#41 [FIX] Recuperado collecstatic para el admin console
  docker/Dockerfile
Labels: fix

#42 [FIX] Docker action compila primero el archivo .env
  .github/workflows/docker.yml
Labels: fix

#43 Docker actions actualizada
  .github/workflows/docker.yml
Labels: fix

#44 [FIX] Añadido checkout poara obtener repositorio
  .github/workflows/docker.yml
Labels: fix

#45 [FIX] Actualizado compose
  docker/docker-compose.yml
Labels: fix
